# Generated by Django 3.2.6 on 2021-08-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210729_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordResetToken',
            field=models.DateTimeField(null=True),
        ),
    ]
