version: '3'

services:
    db:
        image: postgres
        container_name: postgres.djangoToDo.docker
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - ~/data/postgres.djangoToDo.docker:/var/lib/postgresql/data
        ports:
            - 127.0.0.1:${DATABASE_PORT}:5432
        networks:
            - global

    mailcatcher:
        image: schickling/mailcatcher
        container_name: mailcatcher.nodejs-express-api.docker
        restart: unless-stopped
        ports:
            - 127.0.0.1:${MAIL_PORT}:1025
            - 127.0.0.1:1080:1080
        networks:
            - global

networks:
    global:
        external: true
