# Generated by Django 3.2.5 on 2021-07-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_alter_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='userId',
            new_name='owner',
        ),
    ]
