# Generated by Django 3.2.5 on 2021-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_rename_userid_todo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
